=== TheGameKnave/angular-boilerplate/tests/translation/translation.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Translation File Schema",
  "type": "object",
  "properties": {
    "Hello world": {
      "type": "string",
      "description": "Main page greeting"
    },
    "Angular Boilerplate": {
      "type": "string",
      "description": "Main page title"
    },
    "v.": {
      "type": "string",
      "description": "Main page version"
    },
    "Example One": {
      "type": "string",
      "description": "Name of component one"
    },
    "Example Two": {
      "type": "string",
      "description": "Name of component two"
    },
    "Switch to {{componentName}}": {
      "type": "string",
      "description": "Main page component swap button text with component name as {{componentName}}"
    },
    "{{componentName}} works!": {
      "type": "string",
      "description": "Success message with component name as {{componentName}}"
    },
    "There are {{count}} components.": {
      "type": "string",
      "description": "Message about the number of components, using a pluralization format"
    }
  },
  "required": [
    "Hello world",
    "Angular Boilerplate",
    "v.",
    "Example One",
    "Example Two",
    "Switch to {{componentName}}",
    "{{componentName}} works!",
    "There are {{count}} components."
  ],
  "additionalProperties": false
}

=== TheGameKnave/angular-boilerplate/client/src/assets/i18n/en.json
{
  "Hello world": "Hello world"
  ,"Angular Boilerplate": "Angular Boilerplate"
  ,"v.": "v."
  ,"Example One": "Example One"
  ,"Example Two": "Example Two"
  ,"Switch to {{componentName}}": "Switch to {{componentName}}"
  ,"{{componentName}} works!": "{{componentName}} works!"
  ,"There are {{count}} components.": "{count, plural, =0 {There are no components.} one {There is 1 component.} other {There are # components.}}"
}
